### ISSUE TITLE
Изменение имени тега аналогично изменению атрибутов

### ISSUE THREAD

**Issue by kizu** [pasaran/yate#213]
Сейчас рефакторю всякое в наноостровах и там часто есть необходимость менять имя тега. Да и в принципе это довольно частая задача на моей практике: когда есть один шаблон, но в зависимости от условий для него используются разные теги.

Хочется механизм, аналогичный тому, как сейчас работает присвоение/изменение атрибутов: чтобы можно было написать (синтаксис и пример произвольный)

```
<span class="button">

    if .href {
        @tagName = 'a'
        @href = .href
        @class += 'button_link'
    }

    if .type {
        @tagName = 'button'
        @type = .type
        @class += 'button_button'
    }
    
    // тут много всякого другого кода
</span>
```

Синтаксис мне не важен, можно или использовать какое-то ключевое слово вроде `tagName` вместо имени атрибута, можно придумать что-то ещё, но логично было бы, чтобы это делалось аналогично тому, как сейчас происходит работа с атрибутами.

**Comment by andychups** [comment]
+1

Тут дубль: https://github.com/pasaran/yate/issues/10

**Comment by pasaran** [comment]
Блин. Я уже эн раз брался за этот таск, думая, что он вроде простой. И все время во что-то упирался.
Вот сейчас смотрю, вроде опять понятно, как делать. Если не наткнусь на что-то сложное, попробую сделать на днях.

**Comment by andychups** [comment]
Крутяк :)

**Comment by pasaran** [comment]
Почти сделал ) Завтра полирну и тесты и все будет )

**Comment by pasaran** [comment]
Как-то так:

    name = .name
    <{ name } class="foo">
        "Hello"
    </>

    <{ .foo }><{ .bar }>Hello</></>

**Comment by pasaran** [comment]
0.0.80

**Comment by pasaran** [comment]
Попозже более красиво сделаю, как с атрибутами.

```
<foo-{ .foo }>
    @bar-{ .bar } = "quu"
</>
```

**Comment by andychups** [comment]
Спасибо
