### ISSUE TITLE
in-memory компиляция шаблона с зависимостями

### ISSUE THREAD

**Issue by RohovDmytro** [pasaran/yate#251]
— Понадобилось скомпилировать шаблон, который использует импорты.
— Соответственно, понадобились .obj файлы этих зависимостей из рантайма, но без возможности записать и считать их с диска.

Возможно добавить в АПИ модуля in-memory генерацию obj файла?

**Comment by pasaran** [comment]
Все возможно. Вопрос только в трудозатратах.
Прямо сейчас у меня, если честно, нет на это времени. Там нужно довольно существенно переделывать схему компиляции.

Пусть issue висит, как будет время, попробую сделать.

**Comment by rogovdm** [comment]
Локально я реализовал у себя это сверх простым способом.

Добавил в параметр `options` поле ´saveObj::bool´. И в месте, где происходит сохранение на диск учитываю это значение. Очень просто. Дефолтное значение можно сделать ´true´.

Примете пулл реквест?

**Comment by pasaran** [comment]
Ну давайте pr, погляжу.

**Comment by loyd** [comment]
А что если для in-memory компиляции пойти таким путём: передавать в `options`, который идёт в  `compile()` какой-нибудь `provide(pathname)`, возвращающий по пути модуль? Если немного поправить `w_deimport` и `w_deinclude`, то должно работать.

@rogovdm Для obj, соответственно, передавать `onast`, который вызывается в месте генерации.

@pasaran Если подход нормальный, то примешь PR?

**Comment by loyd** [comment]
Добавлю тестов и документацию и уже тогда PR.

Интерфейс ломать не стал, только расширил сигнатуру.
Со стороны пользователя in-memory выглядит довольно посто:
```javascript
var main = fs.readFileSync('main.yate', 'utf8');
var hello = fs.readFileSync('hello.yate', 'utf8');

// Компилируем модуль.
// Можно добавить filename для лучшего вывода ошибок, иначе <anonymous>
var mod = yate.compile({input: hello, saveObj: false});
// Компилируем main.
var res = yate.compile({input: main, modules: {hello: mod.obj}});
```
