### ISSUE TITLE
Предикат не добавляет специфичности матчам

### ISSUE THREAD

**Issue by andychups** [pasaran/yate#255]
Парни, привет!

Давно хотелось обсудить особенность отсутствия специфичности предикатов.

```
{
  "person": {
      "name": "World"
  }
}
```

```
match / {
    apply .person
}

match .person[.name == 'World'] {
    "3"
}

match .person[.name] {
    "2"
}

match .person {
    "1"
}
```

Выведет 1. 

Обходить можно правильным порядком, но это так себе решение:

```
match / {
    apply .person
}

match .person {
    "1"
}

match .person[.name] {
    "2"
}

match .person[.name == 'World'] {
    "3"
}
```
Выведет 3. 

Поиграть можно тут: https://f-o-r.github.io/yate-playground/?gistId=09635a70a6cafba3ccb1d01b9f3d6c17

Несколько вопросов:

1. Было ли так задумано? Если да, то почему?
2. Если исправить, то что можем огрести?
3. На сколько сложная правка и сколько она, примерно, займет по времени?

**Comment by igorz-** [comment]
XSLT для данной ситуации выведет "2". Причем независимо: использовать атрибуты или вложенные ноды.
```xslt
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:template match="person[name/text()='World']">
     <p>3</p>
</xsl:template>
<xsl:template match="person[name]">
     <p>2</p>
</xsl:template>
<xsl:template match="person">
     <p>1</p>
</xsl:template>
</xsl:stylesheet>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<person>
    <name>World</name>
</person>
```

**Comment by pasaran** [comment]
1. Да, так было задумано. Потому что специфичность очень неочевидная штука, явный порядок шаблонов намного прозрачнее. Особенно если добавить сюда несколько модулей через include/import.
2. Очевидно, что нарушится обратная совместимость и почти наверняка у всех что-то сломается.
3. Если не учитывать, что это вообще не нужно делать, то. Хз. Там много нюансов будет. Сейчас матчинг ведется довольно просто: есть хэш по имени моды, внутри хэш по имени ноды, внутри массив шаблонов. Этот массив шаблонов можно отсортировать как угодно и это не очень сложно. А поменять вообще схему матчинга — сложно.

**Comment by andychups** [comment]
Вопрос себя исчерпал. Закрою. Спасибо!
