### ISSUE TITLE
Ошибка в работе предиката с отрицательным числом.

### ISSUE THREAD

**Issue by pavelrevers** [pasaran/yate#257]
Код тут: https://f-o-r.github.io/yate-playground/?gistId=99709229bfce1fb25225b8d7d814adba

**Comment by pasaran** [comment]
0.0.81

Забавный баг. Как его за все эти года не нашли — удивительно )

**Comment by alexeyten** [comment]
Ну, дык, кому нужны отрицательные числа? :)
